# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

class f_PyStruct(object):
    def setupUi(self, f_PyStruct):
        if not f_PyStruct.objectName():
            f_PyStruct.setObjectName(u"f_PyStruct")
        f_PyStruct.setWindowModality(Qt.NonModal)
        f_PyStruct.resize(1471, 909)
        f_PyStruct.setMinimumSize(QSize(1471, 908))
        icon = QIcon()
        icon.addFile(u"./assets/iconos/Logo.png", QSize(), QIcon.Normal, QIcon.Off)
        f_PyStruct.setWindowIcon(icon)
        f_PyStruct.setLayoutDirection(Qt.LeftToRight)
        f_PyStruct.setAutoFillBackground(False)
        f_PyStruct.setStyleSheet(u"background-color: rgb(213, 213, 213);")
        self.nuevo = QAction(f_PyStruct)
        self.nuevo.setObjectName(u"nuevo")
        icon1 = QIcon()
        icon1.addFile(u"./assets/iconos/Nuevo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.nuevo.setIcon(icon1)
        self.abrir = QAction(f_PyStruct)
        self.abrir.setObjectName(u"abrir")
        icon2 = QIcon()
        icon2.addFile(u"./assets/iconos/Insertar.png", QSize(), QIcon.Normal, QIcon.Off)
        self.abrir.setIcon(icon2)
        self.guardar = QAction(f_PyStruct)
        self.guardar.setObjectName(u"guardar")
        icon3 = QIcon()
        icon3.addFile(u"./assets/iconos/Guardar.png", QSize(), QIcon.Normal, QIcon.Off)
        self.guardar.setIcon(icon3)
        self.guardarComo = QAction(f_PyStruct)
        self.guardarComo.setObjectName(u"guardarComo")
        icon4 = QIcon()
        icon4.addFile(u"./assets/iconos/GuardarComo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.guardarComo.setIcon(icon4)
        self.cerrar = QAction(f_PyStruct)
        self.cerrar.setObjectName(u"cerrar")
        icon5 = QIcon()
        icon5.addFile(u"./assets/iconos/Cerrar.png", QSize(), QIcon.Normal, QIcon.Off)
        self.cerrar.setIcon(icon5)
        self.copiar = QAction(f_PyStruct)
        self.copiar.setObjectName(u"copiar")
        icon6 = QIcon()
        icon6.addFile(u"./assets/iconos/Copiar.png", QSize(), QIcon.Normal, QIcon.Off)
        self.copiar.setIcon(icon6)
        self.pegar = QAction(f_PyStruct)
        self.pegar.setObjectName(u"pegar")
        icon7 = QIcon()
        icon7.addFile(u"./assets/iconos/Pegar.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pegar.setIcon(icon7)
        self.cortar = QAction(f_PyStruct)
        self.cortar.setObjectName(u"cortar")
        icon8 = QIcon()
        icon8.addFile(u"./assets/iconos/Cortar.png", QSize(), QIcon.Normal, QIcon.Off)
        self.cortar.setIcon(icon8)
        self.insertar = QAction(f_PyStruct)
        self.insertar.setObjectName(u"insertar")
        self.insertar.setIcon(icon2)
        self.actionEliminar = QAction(f_PyStruct)
        self.actionEliminar.setObjectName(u"actionEliminar")
        self.eliminar = QAction(f_PyStruct)
        self.eliminar.setObjectName(u"eliminar")
        icon9 = QIcon()
        icon9.addFile(u"./assets/iconos/Eliminar.png", QSize(), QIcon.Normal, QIcon.Off)
        self.eliminar.setIcon(icon9)
        self.estadoLicencia = QAction(f_PyStruct)
        self.estadoLicencia.setObjectName(u"estadoLicencia")
        icon10 = QIcon()
        icon10.addFile(u"./assets/iconos/Licencia.png", QSize(), QIcon.Normal, QIcon.Off)
        self.estadoLicencia.setIcon(icon10)
        self.documentacion = QAction(f_PyStruct)
        self.documentacion.setObjectName(u"documentacion")
        icon11 = QIcon()
        icon11.addFile(u"./assets/iconos/Documentacion.png", QSize(), QIcon.Normal, QIcon.Off)
        self.documentacion.setIcon(icon11)
        self.actualizaciones = QAction(f_PyStruct)
        self.actualizaciones.setObjectName(u"actualizaciones")
        icon12 = QIcon()
        icon12.addFile(u"./assets/iconos/Actualizar.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actualizaciones.setIcon(icon12)
        self.cerrarSesion = QAction(f_PyStruct)
        self.cerrarSesion.setObjectName(u"cerrarSesion")
        icon13 = QIcon()
        icon13.addFile(u"./assets/iconos/CerrarSesion.png", QSize(), QIcon.Normal, QIcon.Off)
        self.cerrarSesion.setIcon(icon13)
        self.cw_FondoPyStruct = QWidget(f_PyStruct)
        self.cw_FondoPyStruct.setObjectName(u"cw_FondoPyStruct")
        self.gridLayout = QGridLayout(self.cw_FondoPyStruct)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gl_ContenedorFunciones = QGridLayout()
        self.gl_ContenedorFunciones.setObjectName(u"gl_ContenedorFunciones")
        self.fr_TablasGraficas = QFrame(self.cw_FondoPyStruct)
        self.fr_TablasGraficas.setObjectName(u"fr_TablasGraficas")
        self.fr_TablasGraficas.setMinimumSize(QSize(931, 831))
        self.fr_TablasGraficas.setFocusPolicy(Qt.TabFocus)
        self.fr_TablasGraficas.setStyleSheet(u"background-color: rgb(250, 250, 250);")
        self.fr_TablasGraficas.setFrameShape(QFrame.StyledPanel)
        self.fr_TablasGraficas.setFrameShadow(QFrame.Raised)
        self.gridLayout_4 = QGridLayout(self.fr_TablasGraficas)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.tw_Pestanas = QTabWidget(self.fr_TablasGraficas)
        self.tw_Pestanas.setObjectName(u"tw_Pestanas")
        self.tw_Pestanas.setEnabled(True)
        self.tw_Pestanas.setTabShape(QTabWidget.Triangular)
        self.tw_Pestanas.setTabsClosable(True)
        self.tw_Pestanas.setMovable(True)
        self.Pestana1 = QWidget()
        self.Pestana1.setObjectName(u"Pestana1")
        self.Pestana1.setInputMethodHints(Qt.ImhNoEditMenu)
        self.gridLayout_3 = QGridLayout(self.Pestana1)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.label = QLabel(self.Pestana1)
        self.label.setObjectName(u"label")
        self.label.setStyleSheet(u"")
        self.label.setInputMethodHints(Qt.ImhNoEditMenu)
        self.label.setPixmap(QPixmap(u"./assets/iconos/fondoPresentacion.png"))
        self.label.setScaledContents(True)

        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)

        self.tw_Pestanas.addTab(self.Pestana1, "")

        self.gridLayout_4.addWidget(self.tw_Pestanas, 0, 0, 1, 1)


        self.gl_ContenedorFunciones.addWidget(self.fr_TablasGraficas, 0, 1, 1, 1)

        self.gridLayout_2 = QGridLayout()
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.fr_SeccionBotones = QFrame(self.cw_FondoPyStruct)
        self.fr_SeccionBotones.setObjectName(u"fr_SeccionBotones")
        self.fr_SeccionBotones.setMinimumSize(QSize(371, 211))
        self.fr_SeccionBotones.setMaximumSize(QSize(371, 211))
        self.fr_SeccionBotones.setCursor(QCursor(Qt.ArrowCursor))
        self.fr_SeccionBotones.setStyleSheet(u"background-color: rgb(250, 250, 250);\n"
"")
        self.fr_SeccionBotones.setFrameShape(QFrame.StyledPanel)
        self.fr_SeccionBotones.setFrameShadow(QFrame.Raised)
        self.b_Importar = QPushButton(self.fr_SeccionBotones)
        self.b_Importar.setObjectName(u"b_Importar")
        self.b_Importar.setGeometry(QRect(10, 10, 111, 41))
        self.b_Importar.setCursor(QCursor(Qt.PointingHandCursor))
        icon14 = QIcon()
        icon14.addFile(u"./assets/iconos/Importar.png", QSize(), QIcon.Normal, QIcon.Off)
        self.b_Importar.setIcon(icon14)
        self.b_Importar.setIconSize(QSize(30, 30))
        self.b_Exportar = QPushButton(self.fr_SeccionBotones)
        self.b_Exportar.setObjectName(u"b_Exportar")
        self.b_Exportar.setGeometry(QRect(10, 60, 111, 41))
        self.b_Exportar.setCursor(QCursor(Qt.PointingHandCursor))
        icon15 = QIcon()
        icon15.addFile(u"./assets/iconos/Exportar.png", QSize(), QIcon.Normal, QIcon.Off)
        self.b_Exportar.setIcon(icon15)
        self.b_Exportar.setIconSize(QSize(30, 30))
        self.b_Predictor = QPushButton(self.fr_SeccionBotones)
        self.b_Predictor.setObjectName(u"b_Predictor")
        self.b_Predictor.setGeometry(QRect(260, 10, 93, 91))
        self.b_Predictor.setCursor(QCursor(Qt.PointingHandCursor))
        icon16 = QIcon()
        icon16.addFile(u"./assets/iconos/Predictor.png", QSize(), QIcon.Normal, QIcon.Off)
        self.b_Predictor.setIcon(icon16)
        self.b_Predictor.setIconSize(QSize(90, 90))
        self.b_Pegar = QPushButton(self.fr_SeccionBotones)
        self.b_Pegar.setObjectName(u"b_Pegar")
        self.b_Pegar.setGeometry(QRect(10, 120, 61, 71))
        self.b_Pegar.setCursor(QCursor(Qt.PointingHandCursor))
        icon17 = QIcon()
        icon17.addFile(u"./assets/iconos/Pegar1.png", QSize(), QIcon.Normal, QIcon.Off)
        self.b_Pegar.setIcon(icon17)
        self.b_Pegar.setIconSize(QSize(70, 70))
        self.b_Copiar = QPushButton(self.fr_SeccionBotones)
        self.b_Copiar.setObjectName(u"b_Copiar")
        self.b_Copiar.setGeometry(QRect(80, 120, 93, 31))
        self.b_Copiar.setCursor(QCursor(Qt.PointingHandCursor))
        self.b_Copiar.setIcon(icon6)
        self.b_Cortar = QPushButton(self.fr_SeccionBotones)
        self.b_Cortar.setObjectName(u"b_Cortar")
        self.b_Cortar.setGeometry(QRect(80, 160, 93, 31))
        self.b_Cortar.setCursor(QCursor(Qt.PointingHandCursor))
        self.b_Cortar.setIcon(icon8)
        self.b_PaletaColores = QPushButton(self.fr_SeccionBotones)
        self.b_PaletaColores.setObjectName(u"b_PaletaColores")
        self.b_PaletaColores.setGeometry(QRect(180, 160, 31, 31))
        self.b_PaletaColores.setCursor(QCursor(Qt.PointingHandCursor))
        icon18 = QIcon()
        icon18.addFile(u"./assets/iconos/A.png", QSize(), QIcon.Normal, QIcon.Off)
        self.b_PaletaColores.setIcon(icon18)
        self.b_PaletaColores.setIconSize(QSize(20, 20))
        self.cb_TipoLetra = QComboBox(self.fr_SeccionBotones)
        self.cb_TipoLetra.addItem("")
        self.cb_TipoLetra.addItem("")
        self.cb_TipoLetra.addItem("")
        self.cb_TipoLetra.addItem("")
        self.cb_TipoLetra.addItem("")
        self.cb_TipoLetra.addItem("")
        self.cb_TipoLetra.addItem("")
        self.cb_TipoLetra.setObjectName(u"cb_TipoLetra")
        self.cb_TipoLetra.setGeometry(QRect(180, 120, 131, 31))
        self.cb_TipoLetra.setCursor(QCursor(Qt.PointingHandCursor))
        self.cb_TamanoLetra = QComboBox(self.fr_SeccionBotones)
        self.cb_TamanoLetra.addItem("")
        self.cb_TamanoLetra.addItem("")
        self.cb_TamanoLetra.addItem("")
        self.cb_TamanoLetra.addItem("")
        self.cb_TamanoLetra.addItem("")
        self.cb_TamanoLetra.addItem("")
        self.cb_TamanoLetra.addItem("")
        self.cb_TamanoLetra.addItem("")
        self.cb_TamanoLetra.addItem("")
        self.cb_TamanoLetra.addItem("")
        self.cb_TamanoLetra.setObjectName(u"cb_TamanoLetra")
        self.cb_TamanoLetra.setGeometry(QRect(310, 120, 51, 31))
        self.cb_TamanoLetra.setCursor(QCursor(Qt.PointingHandCursor))
        self.b_Negrilla = QPushButton(self.fr_SeccionBotones)
        self.b_Negrilla.setObjectName(u"b_Negrilla")
        self.b_Negrilla.setGeometry(QRect(230, 160, 21, 28))
        self.b_Negrilla.setCursor(QCursor(Qt.PointingHandCursor))
        icon19 = QIcon()
        icon19.addFile(u"./assets/iconos/N.png", QSize(), QIcon.Normal, QIcon.Off)
        self.b_Negrilla.setIcon(icon19)
        self.b_Negrilla.setIconSize(QSize(15, 15))
        self.b_Cursiva = QPushButton(self.fr_SeccionBotones)
        self.b_Cursiva.setObjectName(u"b_Cursiva")
        self.b_Cursiva.setGeometry(QRect(250, 160, 21, 28))
        self.b_Cursiva.setCursor(QCursor(Qt.PointingHandCursor))
        icon20 = QIcon()
        icon20.addFile(u"./assets/iconos/K.png", QSize(), QIcon.Normal, QIcon.Off)
        self.b_Cursiva.setIcon(icon20)
        self.b_Cursiva.setIconSize(QSize(15, 15))
        self.b_Subrayado = QPushButton(self.fr_SeccionBotones)
        self.b_Subrayado.setObjectName(u"b_Subrayado")
        self.b_Subrayado.setGeometry(QRect(270, 160, 21, 28))
        self.b_Subrayado.setCursor(QCursor(Qt.PointingHandCursor))
        icon21 = QIcon()
        icon21.addFile(u"./assets/iconos/S.png", QSize(), QIcon.Normal, QIcon.Off)
        self.b_Subrayado.setIcon(icon21)
        self.b_Subrayado.setIconSize(QSize(15, 15))
        self.b_Izquierda = QPushButton(self.fr_SeccionBotones)
        self.b_Izquierda.setObjectName(u"b_Izquierda")
        self.b_Izquierda.setGeometry(QRect(290, 160, 21, 28))
        self.b_Izquierda.setCursor(QCursor(Qt.PointingHandCursor))
        icon22 = QIcon()
        icon22.addFile(u"./assets/iconos/Izquierda.png", QSize(), QIcon.Normal, QIcon.Off)
        self.b_Izquierda.setIcon(icon22)
        self.b_Izquierda.setIconSize(QSize(15, 20))
        self.b_Centrado = QPushButton(self.fr_SeccionBotones)
        self.b_Centrado.setObjectName(u"b_Centrado")
        self.b_Centrado.setGeometry(QRect(310, 160, 21, 28))
        self.b_Centrado.setCursor(QCursor(Qt.PointingHandCursor))
        icon23 = QIcon()
        icon23.addFile(u"./assets/iconos/Centro.png", QSize(), QIcon.Normal, QIcon.Off)
        self.b_Centrado.setIcon(icon23)
        self.b_Centrado.setIconSize(QSize(15, 20))
        self.b_Derecha = QPushButton(self.fr_SeccionBotones)
        self.b_Derecha.setObjectName(u"b_Derecha")
        self.b_Derecha.setGeometry(QRect(330, 160, 21, 28))
        self.b_Derecha.setCursor(QCursor(Qt.PointingHandCursor))
        icon24 = QIcon()
        icon24.addFile(u"./assets/iconos/Derecha.png", QSize(), QIcon.Normal, QIcon.Off)
        self.b_Derecha.setIcon(icon24)
        self.b_Derecha.setIconSize(QSize(15, 20))
        self.fr_Graficar = QFrame(self.fr_SeccionBotones)
        self.fr_Graficar.setObjectName(u"fr_Graficar")
        self.fr_Graficar.setGeometry(QRect(140, 10, 111, 91))
        self.fr_Graficar.setStyleSheet(u"QFrame{\n"
"	border: 2px solid #848484;\n"
"}")
        self.fr_Graficar.setFrameShape(QFrame.StyledPanel)
        self.fr_Graficar.setFrameShadow(QFrame.Raised)
        self.b_graficar = QPushButton(self.fr_Graficar)
        self.b_graficar.setObjectName(u"b_graficar")
        self.b_graficar.setGeometry(QRect(10, 10, 91, 51))
        self.b_graficar.setStyleSheet(u"")
        icon25 = QIcon()
        icon25.addFile(u"./assets/iconos/Graficar.png", QSize(), QIcon.Normal, QIcon.Off)
        self.b_graficar.setIcon(icon25)
        self.b_graficar.setIconSize(QSize(55, 50))
        self.cb_TipoGrafica = QComboBox(self.fr_Graficar)
        self.cb_TipoGrafica.addItem("")
        self.cb_TipoGrafica.addItem("")
        self.cb_TipoGrafica.setObjectName(u"cb_TipoGrafica")
        self.cb_TipoGrafica.setGeometry(QRect(10, 60, 91, 21))
        self.cb_TipoGrafica.setLayoutDirection(Qt.LeftToRight)
        self.cb_TipoGrafica.setStyleSheet(u"border: 0px;")
        self.cb_TipoGrafica.setIconSize(QSize(100, 100))
        self.b_Qnegrilla = QPushButton(self.fr_SeccionBotones)
        self.b_Qnegrilla.setObjectName(u"b_Qnegrilla")
        self.b_Qnegrilla.setGeometry(QRect(230, 190, 21, 20))
        icon26 = QIcon()
        icon26.addFile(u"./assets/iconos/QN.png", QSize(), QIcon.Normal, QIcon.Off)
        self.b_Qnegrilla.setIcon(icon26)
        self.b_Qnegrilla.setIconSize(QSize(15, 15))
        self.b_Qcursiva = QPushButton(self.fr_SeccionBotones)
        self.b_Qcursiva.setObjectName(u"b_Qcursiva")
        self.b_Qcursiva.setGeometry(QRect(250, 190, 21, 20))
        self.b_Qcursiva.setCursor(QCursor(Qt.PointingHandCursor))
        icon27 = QIcon()
        icon27.addFile(u"./assets/iconos/QK.png", QSize(), QIcon.Normal, QIcon.Off)
        self.b_Qcursiva.setIcon(icon27)
        self.b_Qcursiva.setIconSize(QSize(15, 15))
        self.b_Qsubrayado = QPushButton(self.fr_SeccionBotones)
        self.b_Qsubrayado.setObjectName(u"b_Qsubrayado")
        self.b_Qsubrayado.setGeometry(QRect(270, 190, 21, 20))
        self.b_Qsubrayado.setCursor(QCursor(Qt.PointingHandCursor))
        icon28 = QIcon()
        icon28.addFile(u"./assets/iconos/QS.png", QSize(), QIcon.Normal, QIcon.Off)
        self.b_Qsubrayado.setIcon(icon28)
        self.b_Qsubrayado.setIconSize(QSize(15, 15))

        self.gridLayout_2.addWidget(self.fr_SeccionBotones, 0, 0, 1, 1)

        self.fr_SeccionArchivos = QFrame(self.cw_FondoPyStruct)
        self.fr_SeccionArchivos.setObjectName(u"fr_SeccionArchivos")
        self.fr_SeccionArchivos.setMinimumSize(QSize(371, 301))
        self.fr_SeccionArchivos.setMaximumSize(QSize(371, 16777215))
        self.fr_SeccionArchivos.setStyleSheet(u"background-color: rgb(250, 250, 250);")
        self.fr_SeccionArchivos.setFrameShape(QFrame.StyledPanel)
        self.fr_SeccionArchivos.setFrameShadow(QFrame.Raised)
        self.tree = QTreeView(self.fr_SeccionArchivos)
        self.tree.setObjectName(u"tree")
        self.tree.setGeometry(QRect(10, 40, 351, 251))
        self.label_3 = QLabel(self.fr_SeccionArchivos)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 10, 131, 16))
        self.label_3.setStyleSheet(u"font-size: 9pt;")

        self.gridLayout_2.addWidget(self.fr_SeccionArchivos, 1, 0, 1, 1)

        self.fr_EspacioTrabajo = QFrame(self.cw_FondoPyStruct)
        self.fr_EspacioTrabajo.setObjectName(u"fr_EspacioTrabajo")
        self.fr_EspacioTrabajo.setMinimumSize(QSize(371, 301))
        self.fr_EspacioTrabajo.setMaximumSize(QSize(371, 16777215))
        self.fr_EspacioTrabajo.setStyleSheet(u"background-color: rgb(250, 250, 250);")
        self.fr_EspacioTrabajo.setFrameShape(QFrame.StyledPanel)
        self.fr_EspacioTrabajo.setFrameShadow(QFrame.Raised)
        self.treePred = QTreeView(self.fr_EspacioTrabajo)
        self.treePred.setObjectName(u"treePred")
        self.treePred.setGeometry(QRect(11, 41, 351, 251))
        self.label_4 = QLabel(self.fr_EspacioTrabajo)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 10, 131, 16))
        self.label_4.setStyleSheet(u"font-size: 9pt;")

        self.gridLayout_2.addWidget(self.fr_EspacioTrabajo, 2, 0, 1, 1)


        self.gl_ContenedorFunciones.addLayout(self.gridLayout_2, 0, 0, 1, 1)


        self.gridLayout.addLayout(self.gl_ContenedorFunciones, 0, 0, 1, 1)

        self.label_2 = QLabel(self.cw_FondoPyStruct)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setStyleSheet(u"QLabel{\n"
"	font-size: 10pt;\n"
"	color: rgb(75, 75, 75);\n"
"}\n"
"")
        self.label_2.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)

        f_PyStruct.setCentralWidget(self.cw_FondoPyStruct)
        self.menuPyStruct = QMenuBar(f_PyStruct)
        self.menuPyStruct.setObjectName(u"menuPyStruct")
        self.menuPyStruct.setGeometry(QRect(0, 0, 1471, 26))
        self.menuPyStruct.setCursor(QCursor(Qt.PointingHandCursor))
        self.menuPyStruct.setLayoutDirection(Qt.LeftToRight)
        self.menuPyStruct.setAutoFillBackground(False)
        self.menuPyStruct.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.menuArchivo = QMenu(self.menuPyStruct)
        self.menuArchivo.setObjectName(u"menuArchivo")
        self.menuArchivo.setCursor(QCursor(Qt.PointingHandCursor))
        self.menuArchivo.setStyleSheet(u"selection-color: rgb(35, 141, 241);")
        self.menuEditar = QMenu(self.menuPyStruct)
        self.menuEditar.setObjectName(u"menuEditar")
        self.menuEditar.setCursor(QCursor(Qt.PointingHandCursor))
        self.menuEditar.setStyleSheet(u"selection-color: rgb(35, 141, 241);")
        self.menuAyuda = QMenu(self.menuPyStruct)
        self.menuAyuda.setObjectName(u"menuAyuda")
        self.menuAyuda.setCursor(QCursor(Qt.PointingHandCursor))
        self.menuAyuda.setFocusPolicy(Qt.TabFocus)
        self.menuAyuda.setStyleSheet(u"selection-color: rgb(35, 141, 241);")
        f_PyStruct.setMenuBar(self.menuPyStruct)

        self.menuPyStruct.addAction(self.menuArchivo.menuAction())
        self.menuPyStruct.addAction(self.menuEditar.menuAction())
        self.menuPyStruct.addAction(self.menuAyuda.menuAction())
        self.menuArchivo.addAction(self.nuevo)
        self.menuArchivo.addAction(self.abrir)
        self.menuArchivo.addAction(self.guardarComo)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.cerrarSesion)
        self.menuArchivo.addAction(self.cerrar)
        self.menuEditar.addAction(self.copiar)
        self.menuEditar.addAction(self.pegar)
        self.menuEditar.addAction(self.cortar)
        self.menuAyuda.addAction(self.estadoLicencia)
        self.menuAyuda.addAction(self.documentacion)

        self.retranslateUi(f_PyStruct)

        self.tw_Pestanas.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(f_PyStruct)
    # setupUi

    def retranslateUi(self, f_PyStruct):
        f_PyStruct.setWindowTitle(QCoreApplication.translate("f_PyStruct", u"Ventana Principal -- PyStruct 2.0", None))
        self.nuevo.setText(QCoreApplication.translate("f_PyStruct", u"Nueva Pesta\u00f1a", None))
#if QT_CONFIG(shortcut)
        self.nuevo.setShortcut(QCoreApplication.translate("f_PyStruct", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.abrir.setText(QCoreApplication.translate("f_PyStruct", u"Abrir", None))
#if QT_CONFIG(shortcut)
        self.abrir.setShortcut(QCoreApplication.translate("f_PyStruct", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.guardar.setText(QCoreApplication.translate("f_PyStruct", u"Guardar", None))
#if QT_CONFIG(shortcut)
        self.guardar.setShortcut(QCoreApplication.translate("f_PyStruct", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.guardarComo.setText(QCoreApplication.translate("f_PyStruct", u"Guardar como", None))
#if QT_CONFIG(shortcut)
        self.guardarComo.setShortcut(QCoreApplication.translate("f_PyStruct", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.cerrar.setText(QCoreApplication.translate("f_PyStruct", u"Cerrar", None))
#if QT_CONFIG(shortcut)
        self.cerrar.setShortcut(QCoreApplication.translate("f_PyStruct", u"Ctrl+W", None))
#endif // QT_CONFIG(shortcut)
        self.copiar.setText(QCoreApplication.translate("f_PyStruct", u"Copiar", None))
#if QT_CONFIG(shortcut)
        self.copiar.setShortcut(QCoreApplication.translate("f_PyStruct", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.pegar.setText(QCoreApplication.translate("f_PyStruct", u"Pegar", None))
#if QT_CONFIG(shortcut)
        self.pegar.setShortcut(QCoreApplication.translate("f_PyStruct", u"Ctrl+V", None))
#endif // QT_CONFIG(shortcut)
        self.cortar.setText(QCoreApplication.translate("f_PyStruct", u"Cortar", None))
#if QT_CONFIG(shortcut)
        self.cortar.setShortcut(QCoreApplication.translate("f_PyStruct", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.insertar.setText(QCoreApplication.translate("f_PyStruct", u"Insertar", None))
        self.actionEliminar.setText(QCoreApplication.translate("f_PyStruct", u"Eliminar", None))
        self.eliminar.setText(QCoreApplication.translate("f_PyStruct", u"Eliminar", None))
        self.estadoLicencia.setText(QCoreApplication.translate("f_PyStruct", u"Cuenta", None))
        self.documentacion.setText(QCoreApplication.translate("f_PyStruct", u"Documentaci\u00f3n", None))
        self.actualizaciones.setText(QCoreApplication.translate("f_PyStruct", u"Actualizaciones", None))
        self.cerrarSesion.setText(QCoreApplication.translate("f_PyStruct", u"Cerrar Sesi\u00f3n", None))
        self.label.setText("")
        self.tw_Pestanas.setTabText(self.tw_Pestanas.indexOf(self.Pestana1), QCoreApplication.translate("f_PyStruct", u"PyStruct 2.0", None))
        self.b_Importar.setText(QCoreApplication.translate("f_PyStruct", u"Importar", None))
        self.b_Exportar.setText(QCoreApplication.translate("f_PyStruct", u"Exportar", None))
        self.b_Predictor.setText("")
        self.b_Pegar.setText("")
        self.b_Copiar.setText(QCoreApplication.translate("f_PyStruct", u"Copiar", None))
        self.b_Cortar.setText(QCoreApplication.translate("f_PyStruct", u"Cortar", None))
        self.b_PaletaColores.setText("")
        self.cb_TipoLetra.setItemText(0, QCoreApplication.translate("f_PyStruct", u"Arial", None))
        self.cb_TipoLetra.setItemText(1, QCoreApplication.translate("f_PyStruct", u"Gill Sans MT", None))
        self.cb_TipoLetra.setItemText(2, QCoreApplication.translate("f_PyStruct", u"Times New Roman", None))
        self.cb_TipoLetra.setItemText(3, QCoreApplication.translate("f_PyStruct", u"Calibri", None))
        self.cb_TipoLetra.setItemText(4, QCoreApplication.translate("f_PyStruct", u"Verdana", None))
        self.cb_TipoLetra.setItemText(5, QCoreApplication.translate("f_PyStruct", u"Algerian", None))
        self.cb_TipoLetra.setItemText(6, QCoreApplication.translate("f_PyStruct", u"Blackadder ITC", None))

        self.cb_TamanoLetra.setItemText(0, QCoreApplication.translate("f_PyStruct", u"8", None))
        self.cb_TamanoLetra.setItemText(1, QCoreApplication.translate("f_PyStruct", u"10", None))
        self.cb_TamanoLetra.setItemText(2, QCoreApplication.translate("f_PyStruct", u"12", None))
        self.cb_TamanoLetra.setItemText(3, QCoreApplication.translate("f_PyStruct", u"14", None))
        self.cb_TamanoLetra.setItemText(4, QCoreApplication.translate("f_PyStruct", u"16", None))
        self.cb_TamanoLetra.setItemText(5, QCoreApplication.translate("f_PyStruct", u"18", None))
        self.cb_TamanoLetra.setItemText(6, QCoreApplication.translate("f_PyStruct", u"20", None))
        self.cb_TamanoLetra.setItemText(7, QCoreApplication.translate("f_PyStruct", u"24", None))
        self.cb_TamanoLetra.setItemText(8, QCoreApplication.translate("f_PyStruct", u"26", None))
        self.cb_TamanoLetra.setItemText(9, QCoreApplication.translate("f_PyStruct", u"28", None))

        self.b_Negrilla.setText("")
        self.b_Cursiva.setText("")
        self.b_Subrayado.setText("")
        self.b_Izquierda.setText("")
        self.b_Centrado.setText("")
        self.b_Derecha.setText("")
        self.b_graficar.setText("")
        self.cb_TipoGrafica.setItemText(0, QCoreApplication.translate("f_PyStruct", u"Lineal", None))
        self.cb_TipoGrafica.setItemText(1, QCoreApplication.translate("f_PyStruct", u"Dispersi\u00f3n", None))

        self.label_3.setText(QCoreApplication.translate("f_PyStruct", u"\u00c1rbol de directorios", None))
        self.label_4.setText(QCoreApplication.translate("f_PyStruct", u"Espacio de Trabajo", None))
        self.label_2.setText(QCoreApplication.translate("f_PyStruct", u"Desarrollado por Ernesto Montes - Oscar Ram\u00edrez", None))
        self.menuArchivo.setTitle(QCoreApplication.translate("f_PyStruct", u"Archivo", None))
        self.menuEditar.setTitle(QCoreApplication.translate("f_PyStruct", u"Editar", None))
        self.menuAyuda.setTitle(QCoreApplication.translate("f_PyStruct", u"Ayuda", None))
    # retranslateUi

